<a href="https://colab.research.google.com/github/yuganshnirwan/Creating-And-Uploading-Datasets/blob/main/pratical_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aarya Yugansh Nirwan
##PRN:25070123004
###Batch EnTC A1

In [1]:
import pandas as pd

data={
    'Roll_No':[1,2,3,4,5],
    'Gender':['F','M','F','M','F'],
    'Department':['ENTC','RA','Mech','AIML','CSE'],
    'CGPA':[9.6,9.5,8.4,8.5,7.6]
}

df=pd.DataFrame(data)

df.to_csv('student_database.csv',index=False)
df

   Roll_No Gender Department  CGPA
0        1      F       ENTC   9.6
1        2      M         RA   9.5
2        3      F       Mech   8.4
3        4      M       AIML   8.5
4        5      F        CSE   7.6

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [3]:
df.shape

(5, 4)

In [4]:
#Access information about a column
df['Department']

0    ENTC
1      RA
2    Mech
3    AIML
4     CSE
Name: Department, dtype: object

In [5]:
#Access information about a row
df.loc[2]

Roll_No          3
Gender           F
Department    Mech
CGPA           8.4
Name: 2, dtype: object

In [6]:
#Data type of each column
df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [7]:
#Perform mean, median, mode
mean=df['CGPA'].mean()
median=df['CGPA'].median()
mode=df['Department'].mode()

print(mean)
print(median)
print(mode)

8.72
8.5
0    AIML
1     CSE
2    ENTC
3    Mech
4      RA
Name: Department, dtype: object

In [8]:
#Insert a new column
df['Grade']=[96,94,81,85,71]
df

   Roll_No Gender Department  CGPA  Grade
0        1      F       ENTC   9.6     96
1        2      M         RA   9.5     94
2        3      F       Mech   8.4     81
3        4      M       AIML   8.5     85
4        5      F        CSE   7.6     71

In [9]:
#Delete a column
df.drop('Gender',axis=1,inplace=True)
df

   Roll_No Department  CGPA  Grade
0        1       ENTC   9.6     96
1        2         RA   9.5     94
2        3       Mech   8.4     81
3        4       AIML   8.5     85
4        5        CSE   7.6     71

In [10]:
#CGPA of Topper
df.loc[0,'CGPA']

np.float64(9.6)

In [11]:
df.iloc[4,2]

np.float64(7.6)

In [12]:
import numpy as np
df=pd.read_csv('/content/Cars93.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/Cars93.csv'

In [13]:
df.size

20

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Department  5 non-null      object
 2   CGPA        5 non-null      float64
 3   Grade       5 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

In [16]:
df.shape

(5, 4)

In [17]:
df.head()

   Roll_No Department  CGPA  Grade
0        1       ENTC   9.6     96
1        2         RA   9.5     94
2        3       Mech   8.4     81
3        4       AIML   8.5     85
4        5        CSE   7.6     71

In [18]:
df.tail()

   Roll_No Department  CGPA  Grade
0        1       ENTC   9.6     96
1        2         RA   9.5     94
2        3       Mech   8.4     81
3        4       AIML   8.5     85
4        5        CSE   7.6     71